In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()
X = iris.data
y = iris.target

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [4]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [5]:
y_pred = model.predict(X_test)

In [6]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.9333333333333333


In [7]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      0.88      0.93        16
           2       0.78      1.00      0.88         7

    accuracy                           0.93        30
   macro avg       0.93      0.96      0.94        30
weighted avg       0.95      0.93      0.94        30



In [8]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 7  0  0]
 [ 0 14  2]
 [ 0  0  7]]
